spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
